package mrk.common.errors;

public enum ErrorCode {
    VALIDATION_ERROR,
    INSUFFICIENT_FUNDS,
    ACCOUNT_FROZEN,
    LIMIT_EXCEEDED,
    IDEMPOTENT_CONFLICT,
    NOT_FOUND,
    UNAUTHORIZED,
    FORBIDDEN,
    INVALID_ACCOUNT,
    INVALID_TRANSACTION,
    INVALID_TRANSACTION_STATE,
    INVALID_AMOUNT,
    INVALID_USER,
    INTERNAL_ERROR
}